Repository MicrosoftDocs/PowerShell-Docs, pull requests merged in 2018-10, with the labels that each got.

#2959 Add Get-Date '%F' option
  reference/6/Microsoft.PowerShell.Utility/Get-Date.md
Labels: Do-Not-Merge, vNext-Docs

#3135 Fixing the -Path Parameter Description for Publish-Module
  reference/5.0/PowershellGet/Publish-Module.md
  reference/5.1/PowershellGet/Publish-Module.md
  reference/6/PowerShellGet/Publish-Module.md
Labels: Do-Not-Merge

#3206 update DebugMode example (values no longer boolean)
  dsc/troubleshooting.md
Labels: Area-DSC
