Repository MicrosoftDocs/PowerShell-Docs, pull requests merged in 2018-11, with the labels that each got.

#3214 Ps module path
  reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
  reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
Labels: Waiting-on-review

#3270 Added a walkthrough to decode a PowerShell command
  reference/docs-conceptual/getting-started/cookbooks/Decode-PowerShell-Command-from-a-Running-Process.md
Labels: Do-Not-Merge

#3308 fix invalid parameter name
  reference/5.0/PackageManagement/Save-Package.md
  reference/5.1/PackageManagement/Save-Package.md
  reference/6/PackageManagement/Save-Package.md
Labels: Area-PowerShellGet, Reference

#3195 Documentation for join-string cmdlet.
  reference/6/Microsoft.PowerShell.Utility/Join-String.md
Labels: vNext-Docs
