Repository MicrosoftDocs/PowerShell-Docs, pull requests merged in 2019-01, with the labels that each got.

#3429 Doc `-UseFuzzyMatching` switch added to `Get-Command`
  reference/6/Microsoft.PowerShell.Core/Get-Command.md
Labels: vNext-Docs

#3590 Related to Issue #2000. Updated Encoding parameter info for all Export-Clixml
  reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md
  reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md
  reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md
  reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md
  reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
Labels: Area-Cmdlets-Utility

#3589 Update PowerShell lifecycles with additional EOL info
  reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Labels: Do-Not-Merge, Review-Shiproom, Waiting-on-review

#3537 Added a remark paragraph according to issue #8607
  reference/6/Microsoft.PowerShell.Management/Test-Path.md
Labels: Area-Cmdlets-Management, Reference

#3563 Added doc about handling reboots
  dsc/TOC.yml
  dsc/configurations/reboot-a-node.md
Labels: Review-PowerShell-Team

#3630 Rewrite Credentials in DSC for clarity
  dsc/configurations/configDataCredentials.md
Labels: Review-PowerShell-Team
