Repository MicrosoftDocs/PowerShell-Docs, pull requests merged in 2019-03, with the labels that each got.

#4002 Update about_Foreach.md
  reference/5.1/Microsoft.PowerShell.Core/About/about_Foreach.md
Labels: Do-Not-Merge, Review-Issue-Author

#4015 Updated Send-MailMessage to say that -subject is no longer required
  reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
Labels: vNext-Docs

#3883 chore: Add EditorConfig for whitepace in IDEs
  .editorconfig
Labels: Review-Shiproom

#4030 add note to reflect that .Net Core doesn't encrypt contents of securestring
  reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
  reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
Labels: vNext-Docs

#4067 Update Write-Output to reflect change in behavior in 6.2 to align with WinPS
  reference/6/Microsoft.PowerShell.Utility/Write-Output.md
Labels: vNext-Docs
